environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: i686-pc-windows-gnu

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.15.1-${env:TARGET}.exe" -FileName "rust-stable.exe"
  - ps: .\rust-stable.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"

build_script:
  - cargo build -v

test_script:
  - SET RUST_BACKTRACE=1
  - cargo test -v
