[package]
name = "spoolq"
version = "0.1.0"
authors = ["Casey Marshall <github@cmars.tech>"]

[dependencies]
chrono = "0.3"
futures = "0.1"
notify = "4.0.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
textnonce = "0.4.1"

